### ISSUE TITLE
virus scan is showing Trojan 

### ISSUE THREAD

**Issue by Salaha1** [RealGoblins/Growtopia-Auto-CCS#3]
i was told about this app and i came to download it, but i had recent experience with the threat "Trojan" and i got hacked by a simular app that had Trojan in it so i am asking for help bcz i dont wanna get hacked another time

**Comment by RealGoblins** [comment]
Hello Salaha1,

We are aware of that some anti-virus software flag the application as a Trojan. Please do note that a wider scan of the executable using VirusTotal would show that **4** out of ~75 engines flag this application as malware. As you probably already know, there are engines of different quality, some are poorly made and would often flag safe software as malware.

I hope this answers your question,
RG

**Comment by Salaha1** [comment]
nvm thanks for this hard working project :)
