### ISSUE TITLE
i asked someone on discord is the program conpatible on windows 7 they said yes

### ISSUE THREAD

**Issue by Salaha1** [RealGoblins/Growtopia-Auto-CCS#4]
i downloaded the zip file on 2 different windows  7 and its not working each pc is giving a different error code the first saying this version of the file is not compatible with your windows version and the second is giving something like "cannot access pastebin download the latest version from realgoblins.eu" but i already downloaded the latest version and it is saying that and a bunch of coding stuff i need help please :)

**Comment by Salaha1** [comment]
P.S i made sure that my windows 7 is up to date and i downloaded .net framework version 4.8 but still getting same results

**Comment by RealGoblins** [comment]
The reason why the app is unable to access pastebin is most likely your Windows firewall blocking all internet connections from the application.

Please do note that updating to windows 10 is recommended. Windows 7 is not anymore supported by Microsoft themselves.
